# Generated by Django 3.2.13 on 2022-06-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('chatId', models.CharField(max_length=15)),
                ('tokenId', models.CharField(max_length=49)),
                ('token', models.CharField(max_length=8)),
                ('vidaToken', models.DateTimeField()),
                ('salt', models.CharField(default='0', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('intentos', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
