# Generated by Django 3.2.13 on 2022-06-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=9)),
                ('carrera', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=30)),
                ('chatId', models.CharField(max_length=9)),
                ('tokenId', models.CharField(max_length=46)),
                ('token', models.CharField(max_length=4)),
                ('vidaToken', models.DateTimeField()),
                ('salt', models.CharField(default='0', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('entrada', models.CharField(max_length=100)),
                ('salida', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maestro', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=255)),
                ('nopersonal', models.CharField(max_length=5)),
                ('correo', models.CharField(max_length=30)),
                ('chatId', models.CharField(max_length=9)),
                ('tokenId', models.CharField(max_length=46)),
                ('token', models.CharField(max_length=4)),
                ('vidaToken', models.DateTimeField()),
                ('salt', models.CharField(default='0', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('intentos', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
