# Generated by Django 4.0.1 on 2022-06-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Salt',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
