# Generated by Django 3.2.13 on 2022-06-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
