# Generated by Django 3.2.13 on 2022-06-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_alter_alumnos_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='token',
            field=models.CharField(max_length=6),
        ),
    ]
