# Generated by Django 3.2.13 on 2022-06-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_alter_maestros_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='correo',
            field=models.CharField(max_length=28),
        ),
    ]
